#!/usr/bin/env bash
CONTAINER_NAME="archdev"
DEBUG="false"

CID=$(docker ps -q -f status=running -f name=^/${CONTAINER_NAME}$)
if [ ! "${CID}" ]; then
  # TODO: Install zsh
  if [ "${DEBUG}" = "true" ]; then
    docker run -it -d \
      -v $HOME:/home/user \
      --name $CONTAINER_NAME \
      archlinux
  else
    docker run -it -d \
      -v $HOME:/home/user \
      --name $CONTAINER_NAME \
      archlinux > /dev/null
  fi
else
  if [ "${DEBUG}" = "true" ]; then
    echo "Conainer already exists. Skipping!"
  fi
fi
unset CID
